---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  {{- with .Values.horizontalPodAutoscaler }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- range $resource, $target := .targets }}
    - type: Resource
      resource:
        name: {{ $resource }}
        target:
          type: {{ $target.type }}
          averageUtilization: {{ $target.averageUtilization }}
    {{- end }}
  {{- end }}
