#!/bin/bash
set -euo pipefail

minikube start $(if [[ $OSTYPE != "linux-gnu"* ]]; then echo "--vm=true"; fi)
minikube addons enable ingress

terraform -chdir=terraform init -input=false
terraform -chdir=terraform plan -input=false -out=tfplan
terraform -chdir=terraform apply -input=false tfplan
rm terraform/tfplan

jenkins=$(terraform -chdir=terraform output -json jenkins | jq -r .)
user=$(terraform -chdir=terraform output -json user | jq -r .)
password=$(terraform -chdir=terraform output -json password | jq -r .)
localstack=$(terraform -chdir=terraform output -json localstack | jq -r .)
bucket=$(terraform -chdir=terraform output -json bucket | jq -r .)
s3_health=$(terraform -chdir=terraform output -json s3_health | jq -r .)
dynamo_health=$(terraform -chdir=terraform output -json dynamo_health | jq -r .)

curl --silent --show-error --output /dev/null --fail --user $user:$password $jenkins
aws --endpoint-url $localstack s3 ls $bucket
curl --silent --show-error --output /dev/null --fail $s3_health
curl --silent --show-error --output /dev/null --fail $dynamo_health