#!/bin/bash
set -euo pipefail

export AWS_S3_ENDPOINT=$(terraform -chdir=terraform output -json localstack | jq -r .)
export AWS_S3_BUCKET=$(terraform -chdir=terraform output -json bucket | jq -r .)
export S3_URL=$(terraform -chdir=terraform output -json s3 | jq -r .)
(cd s3 && go test ./... -cover -race)

export AWS_DYNAMO_ENDPOINT=$(terraform -chdir=terraform output -json localstack | jq -r .)
export AWS_DYNAMO_TABLE=$(terraform -chdir=terraform output -json table | jq -r .)
export DYNAMO_URL=$(terraform -chdir=terraform output -json dynamo | jq -r .)
(cd dynamo && go test ./... -cover -race)