{
 "title": "CLI",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Success Share",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(devops_playground_cli_requests_count{success=\"true\"}) by (path, method) / sum(devops_playground_cli_requests_count) by (path, method)",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(devops_playground_cli_requests_latency_bucket) by (le)",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "99th Percentile",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(devops_playground_cli_requests_latency_bucket) by (le, path, method))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "50th Percentile",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(devops_playground_cli_requests_latency_bucket) by (le, path, method))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  }
 ]
}