{
 "title": "Gateway",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "SLI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(devops_playground_gateway_requests_success[$__rate_interval])) by (deployment) / sum(rate(devops_playground_gateway_requests_total[$__rate_interval])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "SLI (5m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(devops_playground_gateway_requests_success[5m])) by (deployment) / sum(rate(devops_playground_gateway_requests_total[5m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Traffic Split (5m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(devops_playground_gateway_requests_total{deployment=\"prod\"}[5m])) / sum(rate(devops_playground_gateway_requests_total[5m]))",
     "legendFormat": "prod"
    },
    {
     "expr": "sum(rate(devops_playground_gateway_requests_total{deployment=\"canary\"}[5m])) / sum(rate(devops_playground_gateway_requests_total[5m]))",
     "legendFormat": "canary"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(devops_playground_gateway_requests_total[$__rate_interval])) by (path, method)",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(devops_playground_gateway_requests_latency_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(devops_playground_gateway_requests_latency_bucket[$__rate_interval])) by (le, path, method))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(devops_playground_gateway_requests_latency_bucket[$__rate_interval])) by (le, path, method))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  }
 ]
}