{
 "title": "S3",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Success Share (5m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloud_playground_s3_requests_count{success=\"true\"}[5m])) / sum(rate(cloud_playground_s3_requests_count[5m]))"
    }
   ]
  },
  {
   "title": "Success Share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cloud_playground_s3_requests_count{success=\"true\"}[$__rate_interval])) / sum(rate(cloud_playground_s3_requests_count[$__rate_interval]))",
     "legendFormat": "Success Share"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cloud_playground_s3_requests_count[$__rate_interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(cloud_playground_s3_requests_latency_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cloud_playground_s3_requests_latency_bucket[$__rate_interval])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "50th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cloud_playground_s3_requests_latency_bucket[$__rate_interval])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"s3\", container=\"s3\"}[$__interval])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"s3\", container=\"s3\"}"
    }
   ]
  }
 ]
}